locals {
  gzip_settings = [
    {
      name = "Generated by default compression policy"
      content_types = [
        "text/html",
        "application/x-javascript",
        "text/css",
        "application/javascript",
        "text/javascript",
        "application/json",
        "application/vnd.ms-fontobject",
        "application/x-font-opentype",
        "application/x-font-truetype",
        "application/x-font-ttf",
        "application/xml",
        "font/eot",
        "font/opentype",
        "font/otf",
        "image/svg+xml",
        "image/vnd.microsoft.icon",
        "text/plain",
        "text/xml",
      ]
      extensions = [
        "css",
        "js",
        "html",
        "eot",
        "ico",
        "otf",
        "ttf",
        "json",
        "svg",
      ]
    },
  ]
}
