locals {
  headers = [
    {
      action      = "set"
      destination = "http.Strict-Transport-Security"
      name        = "Generated by force TLS and enable HSTS"
      source      = "\"max-age=300\""
      type        = "response"
    },
  ]
}
