---
name: Release - Validate

on:
  pull_request_target:
    branches:
      - main

jobs:
  release-validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Lint PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            refactor
            revert
            chore
            docs
          requireScope: false
